### ISSUE TITLE
Undesired automatic update of the file manager (Simple File Manager) during AOSP update

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#117]
Hello.

Yesterday I installed the latest android AOSP 12.1 update on the Volla. All went well. However, this resulted in Simple File Manager Pro being updated to version 6.16.1 which has significant issues. For example https://github.com/SimpleMobileTools/Simple-File-Manager/issues/757 i opened. Before, I was with version 6.16.0 which worked well. And i don't know if (when) the problems of SFM will be solved.

It is not possible to uninstall updates since Simple File Manager 6.16.1 is the base for the latest AOSP 12.1 whereas it is possible when an update of SFM isn't the first.

Do you have a solution to revert to SFM 6.16.0 ?

It would be desirable for Simplemobiletools, when there is an Android AOSP update, to keep the current version on the Volla and not to automatically update with the most recent version as in my case with Simple File Manager.

Because also, if I update my Volla 22 with the next AOSP, simple file manager 6.16.1 risks being installed if the issue  is not fixed, which I do not want (keep SFM 6.16.0 as a base on the next AOSP on Volla 22).

**Comment by wurzer** [comment]
A critical bug of Simple File Manager is not known. There was a false report on F-Droid in the past regarding the use of the PDF display. However, this false report has since been removed. If you no longer want to use Simple File Manager, you can remove it via security mode and replace it with another file manager of your choice.
