### ISSUE TITLE
Status and outlook for broken Miracast streaming (Volla Phone of 1st generation, Volla Phone X)

### ISSUE THREAD

**Issue by aryoda** [HelloVolla/volla-os-beta-test#158]
As described in the [release notes](https://github.com/HelloVolla/volla-os-beta-test/wiki/Volla-OS-Release-Notes) Miracast does not work and I can confirm this for my Volla Phone 1 using a Samsung GC95a (model 2021): The connection can be established (and auto-disconnects after about 30 secs) but does neither show the phone screen nor the audio is playing. Another test phone (Moto G5) did work with the same TV.

Could you please give me a little bit more details about:

- What is the the reason for the broken miracast?
- Is there a chance to fix this (and if yes: when?)?

**Comment by wurzer** [comment]
The devices can establish a streaming connection but the encoding seems to be borken. This is an an impact for the system update. We are still investigating, how we can fix ist.

**Comment by wurzer** [comment]
@techyminati Maybe you explain it better

**Comment by techyminati** [comment]
Hi @aryoda ,

* The Miracast is broken because the MediaTek's OMX Encoder `OMX.MTK.VIDEO.ENCODER.AVC` is broken for MT6763 Platform with Q Blobs (on Which Volla Phone 1 & X runs), hence due to that mtk's encoder/decoders are failing to provide WFD (Miracast), and all you see is a black screen with distortion. The MediaTek Vendor binaries (or drivers in simple language) we have are from Android 10 from MediaTek, hence this is why we have this issue on latest VollaOS 12. 

* We're working on our own implementation to fix this, there's no confirmation and an exact date about this, work is in progress. 

Thank you and have a nice day!
