### ISSUE TITLE
Provide alternative to http://connectivitycheck.volla.tech/ to keep Wi-Fi working when Volla server is down

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/volla-os-beta-test#176]
Please can you either define a fallback URL for the captive portal or add an ability to disable the portal and choose between them so that when the Volla server is down users can still use Wi-Fi?

For more information about possible options please refer to this page:
https://gearjail.neocities.org/pdacaptport

**Comment by CubedApple** [comment]
Good idea, thank you. Seems related to my original issue (and panic) which has now been closed. Just linking it here:
https://github.com/HelloVolla/volla-os-beta-test/issues/175

**Comment by techyminati** [comment]
@k-kirill Since you have *alot* of questions about that if this patch was actually fixed or not (You asked this on telegram group alot of times), I'm linking down our fixes here -

Please check - https://github.com/HelloVolla/android_vendor_volla/blob/volla-14.0/overlay/packages/modules/NetworkStack/res/values/config.xml#L8

We have specifically defined two alternative captive fallback URLs
which is

1. connectivity-check.ubuntu.com
2. conncheck.opensuse.org<

I'm attaching the whole patch which was merged in internal codebase -

```
From 1a51df414e27aa525362b871bc9ec84dd61b573e Sun Jul 14 17:45:21 2024
From: Aryan Sinha <sinha.aryan03@gmail.com>
Date: Sun, 14 Jul 2024 17:45:21 +0000
Subject: [PATCH] volla: Add fallback URLs to use for detecting captive portals

Description: When volla captive portal goes offline, it shows a false notification
                     about internet not working, hence adding fallback

---
 .../modules/NetworkStack/res/values/config.xml   | 16 ++++++++++++++++
 1 file changed, 16 insertions(+)

diff --git a/overlay/packages/modules/NetworkStack/res/values/config.xml b/overlay/packages/modules/NetworkStack/res/values/config.xml
index 2a1d7eb..11cb913 100644
--- a/overlay/packages/modules/NetworkStack/res/values/config.xml
+++ b/overlay/packages/modules/NetworkStack/res/values/config.xml
@@ -1,5 +1,21 @@
 <?xml version="1.0" encoding="utf-8"?>
 <resources>
+    <!-- HTTP URL for network validation, to use for detecting captive portals. -->
     <string name="default_captive_portal_http_url" translatable="false">http://connectivitycheck.volla.tech/generate_204</string>
+    <!-- HTTPS URL for network validation, to use for confirming internet connectivity. -->
     <string name="default_captive_portal_https_url" translatable="false">https://connectivitycheck.volla.tech/generate_204</string>
+    
+        <!-- List of fallback URLs to use for detecting captive portals. -->
+    <string-array name="default_captive_portal_fallback_urls" translatable="false">
+        <item>http://connectivity-check.ubuntu.com</item>
+        <item>https://connectivity-check.ubuntu.com</item>
+        <item>http://conncheck.opensuse.org</item>
+        <item>https://conncheck.opensuse.org</item>
+    </string-array>
+    <string-array name="config_captive_portal_fallback_urls" translatable="false">
+        <item>http://connectivity-check.ubuntu.com</item>
+        <item>https://connectivity-check.ubuntu.com</item>
+        <item>http://conncheck.opensuse.org</item>
+        <item>https://conncheck.opensuse.org</item>
+    </string-array>
 </resources>
-- 
GitLab

```


@k-kirill the above patch was prepared on July 14th 2024 itself, and was merged in codebase a week after, However we still noticed that fallback was not working, after more deep investigation we found out that the "fallback" code from Android Opensource side is broken itself - This means that we have to rewrite the logic for it all by ourselves, this is a tedious task & requires much effors to do so. However we are already working on this, but its time consuming and requires exhaustive research to do so, We have to modify the entire NetworkStack and find our relevant code to fix it. 

@k-kirill Please note, we take all our efforts to fix every issue which is reported by the customer, no issue is closed without proper fixes or investigation, Regarding the fallback logic re-implementation, we already have the issue ticket open on internal gitlab, which is being worked on.


Thankyou very much and have a nice day ahead.
