### ISSUE TITLE
Display corners makes RDP apps useless

### ISSUE THREAD

**Issue by ghost** [HelloVolla/volla-os-beta-test#31]
When you try to connect with a RDP app to a remote Windows maschine, you will miss the Startbutton, window decorations and the tray area. Would say you will have kinda same experience with other OS. A workaround could be, to forcefully trim such apps to max. full HD resolution.

**Comment by wurzer** [comment]
This looks like an issue of the app, not the operating system. What app are you using?

**Comment by 0xOGeek** [comment]
aFreeRDP, Microsoft RDP Client, doesn't matter. The problem is the cropped screen. There is no compensation from OS side.
Maybe there is an API in Android which Apps need to use to ask for "full visible screen resolution"? Never heard of but if it is there, i will be happy to report to the App developers.
