### ISSUE TITLE
Unable to Upgrade to latest Volla OS version ?!

### ISSUE THREAD

**Issue by 0xOGeek** [HelloVolla/volla-os-beta-test#47]
Under "Updater" it shows me "Android 10, 15. August 2021" last check was now.
But it still offers me 2 Updates:

VollaOS 10.0, 26. Jul. 2021
VollaOS 10.0, 16. Aug. 2021

So in theory i should be able to install at least the August Update, but it fails over and over.
How to get rid of the July update or both?

**Comment by wurzer** [comment]
Thanks for this report. This is the expected behaviour…

**Comment by saidinesh5** [comment]
Hi, This is a critical bug for users that have wiped the data partition after upgrading to Volla OS 10.0.
The bug is fixed in newer builds of 10.0  but we are working on a fix for existing users who can't 
We are working on a fix for this.

**Comment by wurzer** [comment]
Maybe it was my misunderstanding. If you install an update, then this update is still visible in the Updater app. This is the expected behavior. If you can't install the recent update, you can do it in the following way:

1. Tap longer on the entry for the update and copy the URL from the contextual menu.
2. Download the archive from any browser.
3. Copy the archive to your SD card
4. Reastart your device in recovery mode
5. Install the update from the SD card

Let me know if you have questions at any point of these steps

**Comment by 0xOGeek** [comment]
Good morning,

 1. I can't remember ever have wiped the data partition after an update.
 2. I followed @wurzer suggestions but it already fail when i try to download the .zip file via browser: nginx/1.14.0 (Ubuntu) gives me an "404 Not Found" for both Updates (26. Jul. 2021 and 16. Aug. 2021).

**Comment by wurzer** [comment]
Ok, if yo haven't wipe the date like me, you should be able to install the update from the updater app. 
I can confirm the 404 error. It seems to be temporary server problem. Please check the URL soon again.

**Comment by 0xOGeek** [comment]
I can't try anymore cause as i wrote: After refreshing the screen in the updater app again (did it yesterday without results), it does not show me any update now.
Just went back to my phone now, unlocked it and tried to have a look again. Now it tells me after login the updater app crashed, so i restarted the phone.
After restart i searched for updates again with the updater app, but nothing new shows up. All good for now.

**Comment by wurzer** [comment]
I'm sorry for this issue. The OTA server is temporarily not available. Please check again later. As soon the server is online again, you can install the update as described above.
