### ISSUE TITLE
The user interface randomly doesn't accept touch events

### ISSUE THREAD

**Issue by wurzer** [HelloVolla/volla-os-beta-test#61]
Some users are reposting about a freezing screen, but it's not yet reproducable:

Details from users are welcome:

1. What was the last action?
2. What can be seen on the display?
3. Is it possible to show the quick settings?
4. Is it possible to reproduce the error?
5. Does the device work again after locking and unlocking?
6. Which apps were installed from which source?
7. Which apps have special rights?
8. Which phone app is used?
9. Which launcher is used?
10. Which version of the operating system is used?
11. Now many apps are installed?
12. How many apps are running in parallel?

Tips:

1. Clear memory and cache of launcher and close app.
2. Co not define MicroSD as internal memory!
3. Activate DuraSpeed and deactivate apps for Volla OS.

**Comment by tux4us** [comment]
What was the last action?
-> The error occurs involuntarily in every case of use

What can be seen on the display?
-> The display freezes in the current state or it performs wild actions. The indicator menu opens and closes wildly and quickly, and apps open. Sometimes the already opened keyboard makes involuntary inputs.

Is it possible to show the quick settings?
-> Sometimes yes as the only still possible operating option, sometimes the entire system is frozen.

Is it possible to reproduce the error?
-> No, the error occurs unpredictably regardless of the operating case

Does the device work again after locking and unlocking?
-> Most of the time this step is helpful, rarely the phone needs to be turned off hard

Which apps were installed from which source?
-> Over 150 apps from F-Droid store and AuroraStore

Which apps have special rights?
-> What is meant by special rights?

Which phone app is used?
-> The error occurs when using any app, unlocking the lock screen, or using the VollaLauncher. The error is not dependent on a specific app here.

Which launcher is used?
-> VollaLauncher

Which version of the operating system is used?
-> VollaOS 9 and 10 (last Update)

Now many apps are installed?
-> over 150

How many apps are running in parallel?
-> one, but sometimes two or three

**Comment by wurzer** [comment]
Thanks for your report, that will help us to find the issue. Regarding special rights: 
Go to system settings, apps and notifications: Here you find special app permissions, like the permission to overlay over other apps. 

Are you familiar with adb and logcat for a system log?

**Comment by tux4us** [comment]
Davx5 (Sync) have special permission.

Yes, i can handle adb and logcat

**Comment by wurzer** [comment]
Awesome. Can you send us a system log and the time or time range, when the error occured? You can attach it right here,  send it to my telegram account or email.

**Comment by Aposke** [comment]
Hello! I've also had this problem multiple times by now. It started after upgrading the system to 10.0 a few months ago.

    What was the last action?
-> Unlocking the screen and trying to do an action (swipe, type on keyboard)
    
    What can be seen on the display?
-> Usually, this happens either when I'm on the app overview page of the launcher or in an app with the keyboard open. Just now, it also happened when I connected the phone via USB (it was unlocked during the connection).

    Is it possible to show the quick settings?
-> No

    Is it possible to reproduce the error?
-> Not consistently

    Does the device work again after locking and unlocking?
-> In all but one case, this worked. Just a few days ago, it locked up on the app overview and only a restart could make the phone screen responsive again.

    Which apps were installed from which source?
-> 21 apps from F-Droid and 1 app from the Aurora store (Discord). Error also happens when all but the built-in apps are deactivated.

    Which apps have special rights?
-> Only system apps (Dialer, Phone, F-Droid) are allowed to do things like Display over other apps or modify system settings

    Which phone app is used?
-> Error occurs independent of app, has occured on the launcher, Telegram, Discord, and the browser (Fennec) so far.

    Which launcher is used?
-> VollaOS Launcher 1.7.2 and earlier

    Which version of the operating system is used?
-> VollaOS 10.0 from December 2021

    Now many apps are installed?
-> 56, 22 of which were installed by me.

    How many apps are running in parallel?
-> I never run more than 2 or 3 apps in parallel

Attached is a screenshot ofthe screen as it appeared as random interface locking made the touchscreen unresponsive and I had to restart the phone completely.
![Screenshot_20211215-124950](https://user-images.githubusercontent.com/26937693/146364621-c57d115c-7292-4097-91a7-d2e5b0783e92.png)

**Comment by Arvind0203** [comment]
Hi,
Thanks for  above details, It'll really help us to investigate this issue if somebody can share the following logs while device is in freeze state.

adb shell dumpsys SurfaceFlinger > SurfaceFlinger_Dump.txt
adb shell dumpsys window > window_Dump.txt
adb pull /data/anr

**Comment by rachyandco** [comment]
i have the same issue.
i was able to get those file (it is a bit tricky to reproduce :) )

[SurfaceFlinger_Dump.txt](https://github.com/HelloVolla/volla-os-beta-test/files/7777393/SurfaceFlinger_Dump.txt)

[window_Dump.txt](https://github.com/HelloVolla/volla-os-beta-test/files/7777394/window_Dump.txt)

I am on Volla 10 brand new, just installed today with minimal sets of apps (about 10). But i had the same issue on Volla 9.

**Comment by rachyandco** [comment]
I have another Volla phone that has no problem at all. the fact that this is happening on one phone irrelevant on Os9 or 10, irrelevant of a clean install, lets me think this is a hardware problem. My phone did receive several shocks from daily use but no visible screen damage.

**Comment by rachyandco** [comment]
this seems very similar to https://forum.fairphone.com/t/touchscreen-freezes-occasionally-and-random-touch-screen-input/62310
and i believe this is a hardware problem

**Comment by wurzer** [comment]
@rachyandco  Please open a ticket in our customer support, that we can exchange the display or complete device. We are also asked beta testers in our telegram channel for beta testers to check Volla OS 10.1 to compare the behaviour.

**Comment by rachyandco** [comment]
@wurzer thanks! ok I will do, as this is my main device, I have ordered a new one anyway.
