### ISSUE TITLE
How to get a working exposure notification API

### ISSUE THREAD

**Issue by toby63** [HelloVolla/volla-os-beta-test#65]
This is needed for many covid19 apps.

While I understand that there are no Google Services available by default, I read that alternatives such as MicroG should support it.
When I tried to install microG, the installation failed.

**Comment by wurzer** [comment]
System Notifications are working on Volla OS even push notifications from services like Signal. You need to enable push notification for the system and for the app.  Please make sure, that you don't have activated the do-not-disturb-mode. 

Only firebase notifications are not working 

For microG you need to "root" your device first. But I can't recommend it for security reasons. 

Please use the COVID apps from F-Droid instead of the Google Play Store respectively Aurora Store.

**Comment by toby63** [comment]
Thank you very much.

> For microG you need to "root" your device first. But I can't recommend it for security reasons.

Good to know.

> Please use the COVID apps from F-Droid instead of the Google Play Store respectively Aurora Store.

Didn't know those exist.
For everyone else searching for this, this is for example a compatible, free fork for the official german app:
https://f-droid.org/de/packages/de.corona.tracing/
