### ISSUE TITLE
How to disable springboard / launcher?

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/volla-os-beta-test#73]
Dear Volla-team,

I feel unpleasant to ask, because I know how proud you are of the Springboard feature. And indeed, a useful "phone search" is very valuable.
However, I can not get used to it. I am missing a regular "Desktop experience". At least a wallpaper of my family has to be on my phone.

I would therefore like to ask, how to disable the Volla launcher in it's "default appearance". E.g. when I close all apps, I want to be on a common F-Droid environment.
If there is no way at all (which would be very sad, since it would contradict the paradigm of "freedom"), then I urgently ask for more customisation options of the Apps-screen within Volla-Launcher (e.g. use system wallpaper, allow re-arrangement of icons / related to https://github.com/HelloVolla/android-launcher-qt/issues/87 )

Thanks for any hints and cooperation in advance!

**Comment by wurzer** [comment]
You have several options to customize the launcher and to replace it:

* Swipe two times to the right to get the launcher settings from the left. You can choose the transparent mode to see a background image, that you have defined in the system settings.
* In the settings group for menus and design you can activate the option to see the app grid instead of the springboard, if you tab on the home button. You can also decide whether and how the apps are grouped.

You can also replace the launcher with any launcher of your choice. We have even pre-installed Trebuchet, a classical one for Android. Call the system settings, apps & notifications, standard apps and start app. Then you can switch the launcher

Enjoy your day!

**Comment by everyusernameistaken123** [comment]
Thanks for the elaborated answer.
I was not successful with the first hint. There is no "transparent" mode. (Volla OS version 11.1-20220719-STABLE-mimameid) Only a slider for "Blur", which has no noticeable impact.
The second option I was already using, but it was not really fulfilling my needs.
The third option, replacing the launcher did the trick. But I could not directly "start the trebuchet app". I needed to select "Advanced" and "Home app" first, then I could change it.

**Comment by wurzer** [comment]
The first entry of the launcher settings might be "Dark mode". Tap on this item to open a menu, swipe to transparent mode and release your finger. I'm sorry, that this setting is not obvious. We use the same approach for the security setting.
