### ISSUE TITLE
Volla - Volla 22  battery charge level

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/volla-os-beta-test#78]
Volla - Volla 22
I can't see the battery charge level when charging the smartphone turned off. Is this normal or what is the method to display it?

**Comment by wurzer** [comment]
Yes, that's the expected behavior. If you turn off the device and connect it to the power plug for charging, you can see the system starting with the volla logo in the charging mode. Then the charging level is shown with an animation for a short time. You can re-activate this view by shortly pressing the power button.

**Comment by gbdomubpkm** [comment]
Indeed, I can display and reactivate the display of the gauge for a few seconds, but afterwards when the screen is completely black, impossible to make the gauge reappear on the Volla and the Volla 22 after a brief press on the power button.

Alone on the volla 22, I have a brief illumination of the notification battery led and that is normal.

Is this the feature you are describing (seeing the charging level **only** for some seconds) ? Where would it be a bug of the last update?

Can you check and confirm for me if this is a bug or not? It is not clear for me.

Thanks again.
