### ISSUE TITLE
MicroG SafetyNet not working

### ISSUE THREAD

**Issue by TubaApollo** [HelloVolla/volla-os-beta-test#93]
SafetyNet Check fails with "CTS profile does not match". I tried with different device profiles. Normally it wouldnt be an issue, but sadly some banking apps need it :/

Device: Volla Phone
Volla OS 11.1

**Comment by wurzer** [comment]
Thanks for your report. This is an issue of microG.

**Comment by Idcrafter** [comment]
It is working with calyxos on a pixel 6 pro and it works on the volla phones if i use magisk with a fix for safetynet with a module as well as hiding root from microG. It isn't fully a Problem of the volla phones or microG it is probably because the volla phone didn't got verified by google therefore can they not do safetynet but wouldn't it be possible to use the gigaset cts profile for it?
